### ISSUE TITLE
Compatability with Universal Pokemon Randomizer ZX?

### ISSUE THREAD

**Issue by HeyItsLollie** [dannye/pokered-gbc#15]
Not sure which repository this is better suited for, but I wanted to ask about it somewhere at least!

When Pokered-GBC is fed through [Universal Pokemon Randomizer ZX](https://github.com/Ajarmar/universal-pokemon-randomizer-zx), even with all settings left unrandomized/unchanged, the resulting ROM crashes upon entering a battle.

This might be due to UPR-ZX recognizing Pokered-GBC as the original Pokemon Red (the rom's header?), something to do with how UPR-ZX applies a "signature" regardless of randomizer settings (randomizing the Pokemon that appears in the New Game introduction with Oak), or something else entirely.

This can be fixed with an IPS patch generated by using an "unrandomized" randomizer-generated ROM as the "original" rom (simply load the rom and then save), and the original pokered-gbc as the "modified" rom. Obviously though, it'd be nice to be able to skip this step.

I've attached a generated "randomizer fix" IPS patch, which should work with the latest commit of Pokered-GBC after feeding it through [UPR-ZX](https://github.com/Ajarmar/universal-pokemon-randomizer-zx).
📎 [pokered-gbc UPR-ZX Signature Crash Patch.zip](https://github.com/dannye/pokered-gbc/files/7235267/pokered-gbc.UPR-ZX.Signature.Crash.Patch.zip)

**Comment by dannye** [comment]
Sorry for such a long wait on getting back to you.

Mixing tools/patches made for different base roms is fundamentally doomed.

Tools like that randomizer were made with binary hacking/hex editing in mind.

In order to play nice with this mod, ideally the randomizer would have to be remade to deal with the assembly source files instead of the binary rom.

Or at the very least, it's really the randomizer's responsibility to add support for this mod (not the other way around).
It is not the responsibility of this mod to be compatible with the randomizer (while it is technically feasible, it is not practical).

**Comment by HeyItsLollie** [comment]
I figured this might be the case, that's understandable. The IPS patch that I attached is a decent enough workaround for my needs. Thank you for answering!
