### ISSUE TITLE
Songs only playing one channel?

### ISSUE THREAD

**Issue by Th-eo** [dannye/pokered-gbc#8]
While playtesting I've noticed the titlescreen and Oak's Lab music to be off. While playing more attention I noticed only one channel seems to be playing. Am I supossed to use the crysaudio branch? Is this a To-do? Anything I could help with?

On a minor note and perhaps unrelated but, this bit of Mateo's Running Shoes code doesn't seem to be compatible with this ([working commit on Yellow](https://github.com/Mr-Gela/poketbd/commit/7dd76c68d7ee70d0ec9354cff0806ad8c66804b4)) and will start returning "_Unable to place 'Main' (ROM0 section) anywhere_".

I'm a bit of a noob and I'm not sure how to begin a pull request but here's something I did that should be on master:
Oak in the opening speech doesn't have it's own palette. I simply created `GetOakPalID` calling `PAL_OAK` instead, in color/oak_intro.asm:

Then called `GetOakPalID` on line 74 of engine/oak_speech.asm, before `ld de,ProfOakPic`.

By the way, anyone trying to compile this, make sure you are on rgbds 3.0 and not higher or lower than that.

**Comment by dannye** [comment]
1. The music works fine for me (the original Red music on master, and the Crystal music on the crysaudio branch both work fine). What emulator are you using?

2. If rgbds complains about not being able to place a section, that _usually_ means that you tried putting more than $4000 bytes of code/data in a bank.
But with this hack, it can also mean that it was unable to place a section at its original address. Drenn wanted it to be a priority to keep as much of the rom unmodified as possible.
So, many sections have a hard-coded address to place the section at (you would usually omit this when declaring a section).
This kind of section is used to place unmodified code/data at its original address regardless of the "shifting" that happens above the section. If the stuff above the section shrinks, the section will still be placed at the original address. If the stuff above the section grows, the build will fail because the section is unable to be placed at its original address (two sections are overlapping). This is a good thing because it stops us from shifting data unintentionally. The benefit of this is that the final rom is still compatible with _some_ hex editing tools, and the address of certain data will still match what people will read about from other documents. But this real only matters to people who are hex editing. Since you are modifying the source, you can simply remove the hard coded addresses in section declarations.
For example, in home.asm, changing:
```
SECTION "LoadMonFrontSprite", ROM0[$1665]
```
to:
```
SECTION "LoadMonFrontSprite", ROM0
```

Be careful though. DON'T modify any of the sections that come before the `SECTION "Main", ROM0` in home.asm. Those sections are very precise, for hardware reasons.

3. Oak does use his own palette in the intro. But instead of being coded in color/oak_intro.asm like the others, it's coded in engine/oak_speech.asm
https://github.com/dannye/pokered-gbc/blob/87abfb77368db2b7a504f916c1a062a801cb22c7/engine/oak_speech.asm#L57

This relates to point 2. If we added all the custom code that is in color/oak_intro.asm directly into engine/oak_speech.asm, we would make the assembly routine longer shifting everything else in the bank down, which we are trying to avoid. So some of the code got moved to another location. However the Oak palette was able to fit in the original routine without making the routine longer, because of other changes.

4. I've been using rgbds v0.2.5 for this hack. I don't see how using v0.3.0 would cause the audio bugs you are experiencing, but it's possible I suppose. Maybe switching to v0.2.5 would fix that.
Regardless, I'm going to update this hack, and my other hacks, today to be compatible with v0.3.7

**Comment by dannye** [comment]
Finally got around to updating this hack to be compatible with rgbds v0.3.8
Closing
